"""empty message

Revision ID: 20e579a0b756
Revises: 
Create Date: 2022-10-18 22:49:44.174015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e579a0b756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_code', sa.String(length=200), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_code')
    )
    op.create_table('school_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_code', sa.String(length=200), nullable=False),
    sa.Column('class_code', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['school_code'], ['school.school_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_code')
    )
    op.create_table('quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exp', sa.Float(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('class_code', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['class_code'], ['school_class.class_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('job', sa.String(length=200), nullable=False),
    sa.Column('school_code', sa.String(length=200), nullable=False),
    sa.Column('class_code', sa.String(length=200), nullable=True),
    sa.Column('qr', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['class_code'], ['school_class.class_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_code'], ['school.school_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('qr'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top', sa.String(length=200), nullable=False),
    sa.Column('bottom', sa.String(length=200), nullable=False),
    sa.Column('hair', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Float(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('quest')
    op.drop_table('school_class')
    op.drop_table('school')
    # ### end Alembic commands ###
