"""empty message

Revision ID: f301833bd087
Revises: 230a4ff3c149
Create Date: 2022-10-04 22:21:43.633249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f301833bd087'
down_revision = '230a4ff3c149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('exp', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'exp')
    # ### end Alembic commands ###
